### ISSUE TITLE
Uploaded files not showing in the mount point

### ISSUE THREAD

**Issue by rdzetroc** [minio/minfs#30] opened 2017-04-19 13:51 UTC
Newly uploaded files are only showing after a remount of the mount point.

Installed MinFS was from minfs-0.0.20170226202056-1.x86_64.rpm

[rdc@instance-1 rancher]$ minfs -V
minfs version 2017-02-26T20-20-56Z

[rdc@instance-1 rancher]$ uname -a
Linux instance-1 3.10.0-514.10.2.el7.x86_64 #1 SMP Fri Mar 3 00:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

[rdc@instance-1 rancher]$ fusermount -V
fusermount version: 2.9.2

[rdc@instance-1 rancher]$ ps ax | grep minfs
22080 ?        Sl     0:07 /sbin/minfs -o rw,dirsync,mode=644 http://instance-1:9001/www  /var/www/html

**Comment by harshavardhana** [comment] 2017-04-19 14:15
You have to upload files through minfs mount point. That is a current limitation.

**Comment by rdzetroc** [comment] 2017-04-19 14:48
Thank you for the quick response. Is this limitation going to be addressed in future release? It would be fantastic to both upload files from browser and MinFS mounted point

**Comment by harshavardhana** [comment] 2017-04-19 15:44
We will keep you updated. We had this support before but removed it to keep the code simpler.

**Comment by dreh23** [comment] 2017-05-11 13:24
I need this feature as well. Any news. Thank you.

**Comment by hackintoshrao** [comment] 2017-05-22 16:44
Need discussion on this.

**Comment by deekoder** [comment] 2017-05-30 16:45
needs discussion on this as a team. @abperiasamy

**Comment by harshavardhana** [comment] 2017-09-22 09:03
Closing as duplicate of #37

**Closed by harshavardhana** 2017-09-22 09:03 UTC
Labels: priority: high
